import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
    server: {
        host: '127.0.0.1', // evita que quede escuchando solo en IPv6 (::1)
    },
    build: {
        rollupOptions: {
            input: {
                main: resolve(__dirname, 'index.html'),
                equipo: resolve(__dirname, 'equipo.html'),
                admin: resolve(__dirname, 'admin.html'),
                roles: resolve(__dirname, 'roles.html'),
                ofertas: resolve(__dirname, 'ofertas.html'),
                logs: resolve(__dirname, 'logs.html'),
                manifesto: resolve(__dirname, 'manifesto.html'),
                contacto: resolve(__dirname, 'contacto.html'),
                'casos-de-exito': resolve(__dirname, 'casos-de-exito.html'),
                'caso-bobo': resolve(__dirname, 'caso-bobo.html'),
                'nuestra-historia': resolve(__dirname, 'nuestra-historia.html'),
                'publicidad-en-medios': resolve(__dirname, 'publicidad-en-medios.html'),
                'automatizacion-de-procesos': resolve(__dirname, 'automatizacion-de-procesos.html'),
                'diseno-de-marca': resolve(__dirname, 'diseno-de-marca.html'),
                'email-marketing': resolve(__dirname, 'email-marketing.html'),
                'gestion-de-redes': resolve(__dirname, 'gestion-de-redes.html'),
                'influencer-marketing': resolve(__dirname, 'influencer-marketing.html'),
                'caso-amlul': resolve(__dirname, 'caso-amlul.html'),
                'caso-lamanso': resolve(__dirname, 'caso-lamanso.html'),
                'caso-marcawell': resolve(__dirname, 'caso-marcawell.html'),
                'caso-angelanavarro': resolve(__dirname, 'caso-angelanavarro.html'),
                'caso-coolbottles': resolve(__dirname, 'caso-coolbottles.html'),
                'caso-gabrielforsach': resolve(__dirname, 'caso-gabrielforsach.html'),
                'caso-grupomimara': resolve(__dirname, 'caso-grupomimara.html'),
                'caso-iventions': resolve(__dirname, 'caso-iventions.html'),
                'caso-munkombucha': resolve(__dirname, 'caso-munkombucha.html'),
                'caso-oxpertacapital': resolve(__dirname, 'caso-oxpertacapital.html'),
                'caso-oxpertaexpress': resolve(__dirname, 'caso-oxpertaexpress.html'),
                'caso-teamder': resolve(__dirname, 'caso-teamder.html'),
                'caso-thecrewel': resolve(__dirname, 'caso-thecrewel.html'),
                'caso-travelperk': resolve(__dirname, 'caso-travelperk.html'),
                'caso-vasquiat': resolve(__dirname, 'caso-vasquiat.html'),
                'caso-wetribu': resolve(__dirname, 'caso-wetribu.html'),
                'caso-velites': resolve(__dirname, 'caso-velites.html'),
                'caso-nutfruit': resolve(__dirname, 'caso-nutfruit.html'),
                'aviso-legal': resolve(__dirname, 'aviso-legal.html'),
                'cookies': resolve(__dirname, 'cookies.html'),
                'privacidad': resolve(__dirname, 'privacidad.html'),
                'img1': resolve(__dirname, 'img1.html'),
                'calendly': resolve(__dirname, 'calendly.html'),
                '404': resolve(__dirname, '404.html'),
            },
        },
    },
});
